### ISSUE TITLE
Google Storage location for downloading installation binaries is not accessible publicly

### ISSUE THREAD

**Issue by vagmi** [ankyra/escape#3]
The [installation documentation](https://escape.ankyra.io/docs/escape-installation/) mentions that I can download the binary from [https://storage.googleapis.com/escape-releases-eu/escape-client/0.21.9/escape-v0.21.9-darwin-amd64.tgz](https://storage.googleapis.com/escape-releases-eu/escape-client/0.21.9/escape-v0.21.9-darwin-amd64.tgz). But the curl response is `Access Denied`.

```
<?xml version='1.0' encoding='UTF-8'?><Error><Code>AccessDenied</Code><Message>Access denied.</Message><Details>Anonymous users does not have storage.objects.get access to escape-releases-eu/escape-client/0.21.9/escape-v0.21.9-darwin-amd64.tgz.</Details></Error>
```

**Comment by bspaans** [comment]
Hi vagmi, 

Good spot! Looks like the documentation is using an old/wrong location and you should be able to get it from here: https://storage.googleapis.com/escape-releases-eu/escape/0.21.9/escape-v0.21.9-darwin-amd64.tgz

Will update the documentation. Thanks for the report!

**Comment by bspaans** [comment]
Change is now live. Thanks again for reporting!
