### ISSUE TITLE
Expose additional escape script variables related to GIT

### ISSUE THREAD

**Issue by eshepelyuk** [ankyra/escape#39]
Currently `escape script` only exposes `$this.revision` variable that is populated with Git commit hash.

It would be great to expose more information about commit to `escape script`

- author, e.g. `$this.git_author`)
- message, e.g. `$this.git_message`) 
- repository URL, e.g. `$this.git_repository`)

**Comment by bspaans** [comment]
I've added `revision_message` and `revision_author`. The repository URL was already available as `repository`.
