### ISSUE TITLE
Why the software history was not kept?

### ISSUE THREAD

**Issue by gustavopinto** [ankyra/escape#4]
Hi there,

I'm a researcher studying software evolution. As part of my current research, I'm studying the implications of open-sourcing a proprietary software, for instance, if the project succeed in attracting newcomers. However, I observed that some projects, like escape, deleted the software history during the transition to open-source.

https://github.com/ankyra/escape/commit/440209b4e372d3b039241b56868b11195b7607a0

Knowing that software history is indispensable for developers (e.g., developers need to refer to history several times a day), I would like to ask escape developers the following four brief questions:

1. Why did you decide to not keep the software history?
2. Do the core developers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
3. Do the newcomers faced any kind of problems, when trying to refer to the old history? If so, how did they solve these problems?
4. How does the lack of history impacted on software evolution? Does it placed any burden in understanding and evolving the software?

Thanks in advance for your collaboration,

Gustavo Pinto, PhD
http://www.gustavopinto.org

**Comment by bspaans** [comment]
Hey Gustavo, 

Sorry it's taken a while to respond to this, but I hope this helps:

1. The codebase was started as an experimental port of a prototype. Once the prototype was getting a bit serious we scrubbed the repo and put it on github. We scrubbed it in case anything internal or embarrassing would end up on the web.
2. The experimental nature of the early codebase meant that the lack of history has never been a problem. 
3. I don't think so. Most of that early code does not exist any more so the relevant history is there in case anyone wants to look at it.
4. We only really ever refer to the history when we're trying to figure out when and why certain behaviour was introduced. This usually only goes back a few commits, but I can imagine this becoming more pressing when you have a lot of contributors. However, I don't think this will become a problem for us as the deleted history is not relevant anymore.

**Comment by bspaans** [comment]
Going to close this, but feel free to reopen if you have any follow-up questions. 

Thanks, Bart

**Comment by gustavopinto** [comment]
Hi @bspaans, thanks for your response! This is more than sufficient :-)

**Comment by bspaans** [comment]
Great, good luck with your research!

**Comment by gustavopinto** [comment]
Hi @bspaans,

thanks once again for answering our research inquiries. We were able to collect 35 responses and we drafted a research paper with the results. The paper was submitted and accepted for the 14th International Conference on Open Source Systems (http://oss2018.org/). You can find the paper [here](http://gustavopinto.org/lost+found/oss2018.pdf). Hope you enjoy reading the paper!

Thanks again,

Gustavo

**Comment by bspaans** [comment]
Hi @gustavopinto, that's really cool, congratulations!
