### ISSUE TITLE
Automatic version resolution fails after release with overriden version.

### ISSUE THREAD

**Issue by eshepelyuk** [ankyra/escape#44]
Version in `escape.yml` is declared like this `0.0.@` and latest version in inventory is `0.0.5`

After running following

    $ escape run release --override-version 0.0.5.0

A new version `0.0.5.0` is released into inventory.

Then, after running this command

    $ escape run release

the next version released to inventory is `0.0.5.1` 

Instead, it should be `0.0.6` to comply with `version` field declared in escape plan.

**Comment by bspaans** [comment]
Fixed in latest-inventory (v0.16.27)
