### ISSUE TITLE
Possibility to cleanup deps directory when calling escape deps fetch

### ISSUE THREAD

**Issue by eshepelyuk** [ankyra/escape#55]
It's would be useful to add `--cleanup` or some similar flag to  `escape deps fetch` command to implement following :  flag will signal `Escape` to check and remove particular dependency subfolder from `deps` directory if dependency was already removed from `escape.yml`.

**Comment by bspaans** [comment]
The use case here is to remove old dependencies

**Comment by eshepelyuk** [comment]
Rather to remove dependencies files that was already removed from `escape.yml`
